### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by 4nc3str4l** [ElrondNetwork/elrond-proxy-go#108]
Hello, the following link is broken on the README.md

**Comment by 4nc3str4l** [comment]
![image](https://user-images.githubusercontent.com/6674976/101081326-3122aa80-35aa-11eb-8819-a818df130266.png)

**Comment by miiu96** [comment]
Hello. Thank you for the feedback.
The problem is fixed now (https://github.com/ElrondNetwork/elrond-proxy-go/pull/110).
