### ISSUE TITLE
Feature request: ESDT token queries

### ISSUE THREAD

**Issue by hiddentao** [ElrondNetwork/elrond-proxy-go#111]
We need methods for querying:

* `/esdt` - Full list of ESDT token identifiers.
* `/esdt/:tokenId` - Information (i.e. owner, supply, config) for a specific token.

These methods will then enable us to build a full token management UI.

**Comment by bogdan-rosianu** [comment]
Hello, @hiddentao !
We have already implemented the endpoints that you mentioned and will be available in future releases.
`proxyUrl/address/erd1alice.../esdt` endpoint returns a list of tokens that an address interacted with.
`proxyUrl/address/erd1alice.../esdt/:tokenId` endpoint returns data about a specific token that a user interacted with. For now, only the balance and some properties are returned.

For now, the full list of ESDT tokens can be fetched from a call to the ESDT Smart Contract address. Also, we are currently working on indexing all ESDT transactions in Elastic Search.
We will probably add more endpoints in regards to ESDT handling. 
Please let us know if you have other data that you would like to fetch from the API for handling token management.

Thank you!

**Comment by hiddentao** [comment]
Thanks. 

Had another look at the code and was able to figure out how to get all tokens as well. I'll put it here for other people to see too:

```
POST https://testnet-gateway.elrond.com/vm-values/string

{
	"scAddress": "erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u",
	"funcName": "getAllESDTTokens",
	"args": []
}
```

**Comment by bogdan-rosianu** [comment]
Yes, that's correct. This endpoint will work and return all the ESDT tokens if there are any or the ESDT is enabled.

**Comment by bogdan-rosianu** [comment]
Hi ! I will close the issue as the endpoint are already implemented and running on the testnet.
