### ISSUE TITLE
/transactions/:hash endpoint does not return full information

### ISSUE THREAD

**Issue by WIttyJudge** [ElrondNetwork/elrond-proxy-go#272]
Hello, @bogdan-rosianu.
When I call /transaction/:hash endpoint, I want to get full information like api.elrond.com does.
E.g. I don't see:
- gasUsed
- fee
- timestamp

With query parameter ``withResult=true`` there is no ``relayedValue``.

Thank you in advance!

**Comment by bogdan-rosianu** [comment]
Hello! 
This data isn't available in proxy (gateway.elrond.com), but only in api.elrond.com. If you want to set up such an instance, please take a look over https://github.com/ElrondNetwork/api.elrond.com as it also fetches data from Elasticsearch.

Thanks!
