### ISSUE TITLE
errors.Is....

### ISSUE THREAD

**Issue by AndreiD** [ElrondNetwork/elrond-proxy-go#289]
https://github.com/ElrondNetwork/elrond-proxy-go/blob/b7a84a565df92594eb0df9f24285d4be82f12a23/observer/nodesProviderFactory.go#L53

ba da sa va intreb si eu p voi. de ce nu folositi camel case ca standard .. toata lumea il foloseste

testing/testHttpServer.go:30:6: type `TestHttpServer` should be `TestHTTPServer` (golint)
type TestHttpServer struct {
     ^
testing/testHttpServer.go:35:6: func NewTestHttpServer should be NewTestHTTPServer (golint)
func NewTestHttpServer() *TestHttpServer {
     ^
testing/testHttpServer.go:407:28: method processRequestVmValue should be processRequestVMValue (golint)
func (ths *TestHttpServer) processRequestVmValue(rw http.ResponseWriter, _ *http.Request) {
                           ^
metrics/statusMetrics.go:19:25: exported func NewStatusMetrics returns unexported type *github.com/ElrondNetwork/elrond-proxy-go/metrics.statusMetrics, which can be annoying to use (golint)
func NewStatusMetrics() *statusMetrics {
                        ^
versions/errors.go:9:5: var `ErrNilApiHandler` should be `ErrNilAPIHandler` (golint)
var ErrNilApiHandler = errors.New("nil api handler")

config/config.go:27:2: struct field `ApiLogging` should be `APILogging` (golint)
	ApiLogging             ApiLoggingConfig
	^
config/config.go:33:6: type `ApiLoggingConfig` should be `APILoggingConfig` (golint)
type ApiLoggingConfig struct {
     ^
observer/baseNodeProvider.go:27:3: var `shardId` should be `shardID` (golint)
		shardId := observer.ShardId
		^
observer/baseNodeProvider.go:94:3: var `shardId` should be `shardID` (golint)
		shardId := observer.ShardId
		^

**Comment by bogdan-rosianu** [comment]
Hello!

First of all, please use English.
Regarding the issues found by the linter, we'll take a look.

**Comment by AndreiD** [comment]
nu vreau
